server:
    port: 8080
spring:
    application:
        name: mapAuthRest
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/Maps
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update